### ISSUE TITLE
failed at installation

### ISSUE THREAD

**Issue by srgvg** [geertj/bluepass#4]
hi,

tried to install (ubuntu 13.04), but miserably failed

I first tried converting this to an ubuntu package (`python setup.py --command-packages=stdeb.command bdist_deb`), but running from there:
- missed the gevent dependency, installed it manually (default ubuntu package)
- then following error

```
  File "/usr/lib/python2.7/dist-packages/bluepass/messagebus.py", line 360, in GEventLoop
    READ = core.READ
AttributeError: 'module' object has no attribute 'READ'
```

Then tried to install it manually with setup.py (using virtualenv):
- same missing dependency gevent
- installed gevent from githun as per requirements (and cython per pip before that)
- got `ImportError: No module named six`, installed it throug pip
- got `ImportError: No module named sip`, tried install it throuh pip, but that setup fails (missing `build/sip/setup.py`)

HTH,

**Comment by geertj** [comment]
Are you using gevent 0.13 by any chance?

You need to use 1.0-rc from gevent.org.

**Comment by srgvg** [comment]
- 0.13.7-0ubuntu1 is the default version on ubuntu 13.04, yes
- in the virtualenv I got gevent (1.0dev)
  (installed as pip install git+git://github.com/surfly/gevent.git@1.0rc2#egg=gevent)

I'll focus on the virtualenv setup from now on.

**Comment by srgvg** [comment]
FYI:

```
$ yolk -l 
Cython          - 0.19.1       - active 
Python          - 2.7.4        - active development (/usr/lib/python2.7/lib-dynload)
argparse        - 1.2.1        - active development (/usr/lib/python2.7)
bluepass        - 0.8.dev      - active 
gevent          - 1.0dev       - active 
greenlet        - 0.4.1        - active 
pip             - 1.3.1        - active 
setuptools      - 0.6c11       - active 
six             - 1.3.0        - active 
wsgiref         - 0.1.2        - active development (/usr/lib/python2.7)
yolk            - 0.4.3        - active 
```

**Comment by geertj** [comment]
Serge, do you still have a problem, or did the change to gevent 1.0-rc2 solve it?

We need proper packages for Ubuntu. It's in the plan.

**Comment by srgvg** [comment]
Geert, i initially already had 1.0-rc2 (in the virtualenv), so no, that doesn't solve it.

**Comment by geertj** [comment]
OK - let me look into it...

**Comment by geertj** [comment]
OK - I missed the last error about "sip", which is giving away the error.

I have updated the install instruction in the README. For Ubuntu:

```
    # apt-get install python-dev cython python-qt4 libdbus-1-dev
    # pip install -r requirements.txt
    # python setup.py install
```

They were still referring to the original Qt bindings that I was using (python-pyside), but i since switched to python-qt4 which is better maintained.

If you want to use a virtualenv (in order not to replace your system provided gevent), then you should create it with --system-site-packages to allow it to use the system Cython and PyQt4. In either case, "pip install -r requirements.txt" should install all the required dependencies.

Please let me know if this works for you.

**Comment by srgvg** [comment]
After a clean chckout of your latest master branch:

``` bash
apt-get install python-dev cython python-qt4 libdbus-1-dev
mkdir virtpython
cd virtpython
virtualenv --system-site-packages bluepass
. bluepass/bin/activate
pip install -r ~/src/bluepass/requirements.txt 
python  ~/src/bluepass/setup.py install
```

This ends with 

``` bash
building 'bluepass.ext.openssl' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c bluepass/ext/openssl.c -o build/temp.linux-x86_64-2.7/bluepass/ext/openssl.o
bluepass/ext/openssl.c:15:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

note: I'm doing this on another host than this afternoon, possibly I don't have the same set of packages.

**Comment by geertj** [comment]
OK, so it seems SSL development files are missing. Can you try "apt-get install libssl-dev"?

**Comment by srgvg** [comment]
OK!, Now it installs and I get the Create Vault screen! Thx!

PS: Maybe now we could look into building a deb package? Feel free to contact me in private.

**Comment by notslang** [comment]
I had the same issue and using `apt-get install libssl-dev` fixed it... this should be added to the readme

**Comment by geertj** [comment]
Installation instructions updated. Thanks for the report.
